export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const CONFIRM_REGISTER_SUCCESS = 'CONFIRM_REGISTER_SUCCESS';
export const CONFIRM_REGISTER_ERROR = 'CONFIRM_REGISTER_ERROR';